directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_290 #Ensure IAM policies does not allow write access without constraints
- CKV_AWS_355 #Ensure no IAM policies documents allow "*" as a statement's resource for restrictable actions
