directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_88 #EC2 instance should not have public IP.
