name: PR Labeler
on:
  pull_request:
    types: [opened]

permissions: read-all
jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
